### ISSUE TITLE
Sending comments sometimes not working

### ISSUE THREAD

**Issue by joguy56** [SanderRonde/VSCode-Gerrit#83] opened 2024-11-08 11:21 UTC
Hello,

Sometimes, I need to send special comments to restart checks jobs, or that kind of stuff, but when I click on send, it does not work.

As an example of what I get:
![image](https://github.com/user-attachments/assets/9c75504a-0c3b-4ddd-8ef7-b45e18797d34)

Same question after simply commenting reviews. My comments are well sent as draft, but I still need my browser to send them effectively. 

I do update the review panel accordingly to the review I am commenting.

Maybe I miss something in the usage of extension, but I wonder what.

**Comment by SanderRonde** [comment] 2024-11-08 11:23
Thanks for the logs, that gives a pretty good indication of where the bug is. Will fix it soon :)

Do you get the same or a similar error when leaving non-patchset-level comments?

**Comment by joguy56** [comment] 2024-11-08 14:49
Yes absolutely !

**Comment by SanderRonde** [comment] 2024-11-10 16:51
A couple of questions since I'm not (directly) able to reproduce it myself:
- Does this happen when you're posting review comments on your own patchsets or on others'?
- What version of Gerrit are you using?
- Is it correct that you're leaving a top-level message (see img) when this happens?
- Could you maybe show just a bit more of the logs? I'm fairly certain that the request triggering this error is a POST request to `/changes/{changeId}/revisions/{revisionId}/review` but would like to verify. In the image you sent I can only see a GET before (which didn't trigger the error after). Also fine if you can just confirm that indeed a POST with a similar URL was sent just before.

Thanks!

![image](https://github.com/user-attachments/assets/1f49cd3b-2b62-42e1-b7a6-28ba7d6bd3df)

**Comment by joguy56** [comment] 2024-11-12 07:51
Before sending more logs, I can certify that when I am posting comments on my own patchsets or review, It does not work.

I am using Gerrit 3.2.7 at the moment (imposed by higher level, not my choice)

I noticed this most of the time when I left a top-level message, yes. Simply because in our process is a way used for launching CI checks automatedly. I never been able to send such comments via the vscode extension.

I will try to get you more logs as soon as I can get them.

Thanks again for your nice work !

Jonathan

**Comment by joguy56** [comment] 2024-11-12 09:24
ah !!! damned. 

I am part of a big structure, and I won’t be able to change this by myself. Need to wait then. 

This will be a known issue for me indeed...

**Comment by SanderRonde** [comment] 2024-11-13 07:48
Ah that's unfortunate. I'll close this issue for now then.

**Closed by SanderRonde** 2024-11-13 07:48 UTC
